# Generated by Django 4.0 on 2023-06-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='nome',
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('cadeira', models.CharField(max_length=100)),
                ('total_estudantes', models.PositiveIntegerField(default=0)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_criadas', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.turma')),
            ],
        ),
    ]
