# Generated by Django 4.0 on 2023-06-05 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_remove_docente_email_remove_docente_nome_turma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_criadas', to='controle.docente'),
        ),
    ]
